-- Migration 009: Intentionally left as a no-op.
--
-- The v1.0.0 configuration direction is ".env as single source of truth",
-- so the integration_configs table is not part of the schema for fresh installs.
-- This migration number is retained to preserve migration ordering/history
-- without creating schema that is immediately removed by migration 010.
